Repository CosmoStat/wf-psf, pull requests merged in 2024-03, with the labels that each got.

#117 Add doc files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEV_WORKFLOW.md
  assets/branching_model.png
  docs/source/index.rst
Labels: documentation

#120 Fix black test failure in CI
  .github/pull_request_template.md
  .github/workflows/ci.yml
  pyproject.toml
  src/wf_psf/data/training_preprocessing.py
  src/wf_psf/psf_models/zernikes.py
  src/wf_psf/run.py
  src/wf_psf/tests/conftest.py
  src/wf_psf/tests/metrics_test.py
  src/wf_psf/tests/test_utils/conftest.py
  src/wf_psf/training/train.py
  src/wf_psf/utils/configs_handler.py
Labels: bug

#111 Bug plotting missing Shape Metrics e2 and R2
  src/wf_psf/plotting/plots_interface.py
  src/wf_psf/tests/metrics_test.py
  src/wf_psf/tests/train_test.py
Labels: bug, enhancement

#129 Fix broken contribution link
  docs/source/index.rst
Labels: bug

#128 Rename SimPSFToolkit.py module
  docs/source/wf_psf.sims.SimPSFToolkit.rst
  docs/source/wf_psf.sims.rst
  papers/Neurips2021_ML4Physics_workshop/notebooks/Neurips2021-ML4Physics_Reconstructions-chromatic-NASA.ipynb
  papers/Neurips2021_ML4Physics_workshop/notebooks/Neurips2021-ML4Physics_Reconstructions.ipynb
  papers/article_IOP/notebooks/DD-features-dataset-examples.ipynb
  papers/article_IOP/notebooks/generate-coherent-dataset-scrip.ipynb
  src/wf_psf/data/training_preprocessing.py
  src/wf_psf/metrics/metrics.py
  src/wf_psf/metrics/metrics_interface.py
  src/wf_psf/psf_models/psf_model_parametric.py
  src/wf_psf/psf_models/psf_model_semiparametric.py
  src/wf_psf/psf_models/psf_models.py
  src/wf_psf/psf_models/tf_layers.py
  src/wf_psf/psf_models/tf_modules.py
  src/wf_psf/psf_models/tf_psf_field.py
  src/wf_psf/sims/psf_simulator.py
  src/wf_psf/utils/utils.py
Labels: enhancement
